#! /usr/bin/env bash
# Used for lf preview of animated webp files with kitty.
# Requirements: xxhash, libwebp installed from Google's repository.

CACHE_LIMIT=51200

file=$1

webpinfo $file | grep ANIM > /dev/null 2> /dev/null
if [[ $? -ne 0 ]];
then
    echo "$file"
    exit 0
fi

cachesize=$(du -s "$HOME/.cache/animated_webp_preview" | cut -f1)
if [[ $cachesize -gt CACHE_LIMIT ]];
then
    rm "$HOME/.cache/animated_webp_preview/*"
fi

fname=($(xxhsum "$file"))
full_fname="$HOME/.cache/animated_webp_preview/$fname"

if [[ -f full_fname ]];
then
    echo "$full_fname"
    exit 0
fi

mkdir -p ~/.cache/animated_webp_preview
webpmux -get frame 2 "$file" -o "$full_fname" 

if [[ $? -eq 0 ]];
then
    echo "$full_fname"
else
    echo "$file"
fi
